version: '3.8'

services:
  jekyll:
    build: .
    image: amirpourmand/al-folio:v0.12.1
    ports:
      - "8080:8080"   # Host:Container
      - "35729:35729"
    volumes:
      - .:/srv/jekyll:cached
    environment:
      - JEKYLL_ENV=development
    restart: unless-stopped
